name: Generate Podcast feed file
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: AndrewParkerTechnicalTester/podcast-generator@main
        
